// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM1eWGcu8WkTstLhQSUzMIrRnMpu4HhoA',
    appId: '1:357571815038:web:89e59ebc24fb46762fda2f',
    messagingSenderId: '357571815038',
    projectId: 'facefpalooza-ff06d',
    authDomain: 'facefpalooza-ff06d.firebaseapp.com',
    storageBucket: 'facefpalooza-ff06d.appspot.com',
    measurementId: 'G-Q2LL2SSE7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpZEkfQEmQpO9pMZ7I1znBwszMxc61VQ',
    appId: '1:357571815038:android:090e828da9b666f22fda2f',
    messagingSenderId: '357571815038',
    projectId: 'facefpalooza-ff06d',
    storageBucket: 'facefpalooza-ff06d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn-HA5qURUSJ8ajcSV8K4IW_PWXHC1Ut8',
    appId: '1:357571815038:ios:2140d038fe0804492fda2f',
    messagingSenderId: '357571815038',
    projectId: 'facefpalooza-ff06d',
    storageBucket: 'facefpalooza-ff06d.appspot.com',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn-HA5qURUSJ8ajcSV8K4IW_PWXHC1Ut8',
    appId: '1:357571815038:ios:2140d038fe0804492fda2f',
    messagingSenderId: '357571815038',
    projectId: 'facefpalooza-ff06d',
    storageBucket: 'facefpalooza-ff06d.appspot.com',
    iosBundleId: 'com.example.facefpalooza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDM1eWGcu8WkTstLhQSUzMIrRnMpu4HhoA',
    appId: '1:357571815038:web:f33a56992feef3e12fda2f',
    messagingSenderId: '357571815038',
    projectId: 'facefpalooza-ff06d',
    authDomain: 'facefpalooza-ff06d.firebaseapp.com',
    storageBucket: 'facefpalooza-ff06d.appspot.com',
    measurementId: 'G-PDSSQD44RK',
  );

}